2025-01-18 15:01:52,577 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2025-01-18 15:01:52,578 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\ADMIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\instabot\bot\bot.py
2025-01-18 15:01:52,578 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2025-01-18 15:01:52,924 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2025-01-18 15:01:53,233 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2025-01-18 15:01:53,661 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2025-01-18 15:01:53,948 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2025-01-18 15:01:53,948 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2025-01-18 15:01:53,948 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2025-01-18 15:01:53,948 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
